# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('accnumber', models.IntegerField()),
            ],
            options={
                'db_table': 'Account details',
            },
        ),
    ]
