# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accnumber',
        ),
        migrations.AddField(
            model_name='branch',
            name='accnumber',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.Branch'),
        ),
    ]
